#ifndef COMPILER_AST_LAYOUT_H
#define COMPILER_AST_LAYOUT_H

enum function_layout {
    FUNCTION_LAYOUT_NAME,
    FUNCTION_LAYOUT_RETURN,
    FUNCTION_LAYOUT_ARGS,
    FUNCTION_LAYOUT_BODY
};

enum variable_layout {
    VARIABLE_LAYOUT_NAME,
    VARIABLE_LAYOUT_TYPE
};

enum struct_layout {
    STRUCT_LAYOUT_NAME,
    STRUCT_LAYOUT_IMPLEMENTS,
    STRUCT_LAYOUT_MEMBERS,
    STRUCT_LAYOUT_STATICS
};

enum interface_layout {
    INTERFACE_LAYOUT_NAME,
    INTERFACE_LAYOUT_ABSTRACTS,
    INTERFACE_LAYOUT_ASSOCIATIONS,
};

#endif //COMPILER_AST_LAYOUT_H